In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from torch import optim

In [2]:
x = torch.Tensor([[0,0],[0,1],[1,0],[1,1]])
y = torch.Tensor([[0,1,1,0]])

In [3]:
n_input = 2
n_hidden = 2
n_output = 1

class network(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(n_input , n_hidden)
        self.out = nn.Linear(n_hidden , n_output)
    
    def forward(self,x):
        x = torch.sigmoid(self.hidden(x))
        x = torch.sigmoid(self.out(x))
        return x

In [4]:
def sigmoid(z):
    return 1/(1+torch.exp(-z))

In [5]:
model = network()

In [6]:
model

network(
  (hidden): Linear(in_features=2, out_features=2, bias=True)
  (out): Linear(in_features=2, out_features=1, bias=True)
)

In [7]:
model(x)

tensor([[0.5850],
        [0.5905],
        [0.6127],
        [0.6166]], grad_fn=<SigmoidBackward>)

In [8]:
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters() , lr = 0.1)

In [9]:
for epoch in range(100):
    optimizer.zero_grad()
    output = model(x)
    loss = criterion(output , y)
    loss.backward()
    optimizer.step()
    print(loss.item())

0.7137036323547363
0.6971072554588318
0.6933162212371826
0.6962496638298035
0.6993333101272583
0.6997619867324829
0.6980748772621155
0.6956965923309326
0.6938026547431946
0.6930046081542969
0.6932940483093262
0.6941583156585693
0.6949064135551453
0.6950643062591553
0.694566547870636
0.6936674118041992
0.6927228569984436
0.6919969916343689
0.6915608644485474
0.6912938356399536
0.6909655332565308
0.6903445720672607
0.6892790794372559
0.6877183318138123
0.6856851577758789
0.683224618434906
0.6803544163703918
0.6770332455635071
0.673160195350647
0.6686069369316101
0.6632703542709351
0.6571164131164551
0.6501930952072144
0.6426055431365967
0.6344757080078125
0.6259071826934814
0.616974949836731
0.6077386736869812
0.598264753818512
0.5886401534080505
0.5789710283279419
0.5693700313568115
0.5599396228790283
0.5507575869560242
0.5418640375137329
0.5332529544830322
0.5248686075210571
0.5166094899177551
0.5083397030830383
0.49990832805633545
0.49117469787597656
0.4820340871810913
0.4724308848381

/home/nilesh/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:2016: UserWarning: Using a target size (torch.Size([1, 4])) that is different to the input size (torch.Size([4, 1])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))


In [10]:
ypred = model(x)
ypred

tensor([[0.0320],
        [0.9604],
        [0.9608],
        [0.0683]], grad_fn=<SigmoidBackward>)

In [11]:
label_units = ypred.detach().numpy()
predictions = ypred > 0.5
predictions.numpy()

array([[0],
       [1],
       [1],
       [0]], dtype=uint8)